version: 2.1

jobs:
  build:
    docker:
      - image: crystallang/crystal:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: shards install
      - run:
          name: Run tests
          command: crystal spec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
